# -*- coding: utf-8 -*-
"""arquitectura_1_clasificador.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/190SV0k0AoY75RzLFX0os28hMl6FKLrjZ
"""

class Clasificador_Conv(nn.Module):
    def __init__(self, autoencoder_conv=None, copy_encoder=True, n1=128, n2=256, p=0.2):
        super().__init__()

        self.n1 = n1
        self.n2 = n2
        self.p = p

        if autoencoder_conv is None:
            print("Creating encoder...")
            self.encoder = nn.Sequential(
                nn.Conv2d(1, 16, kernel_size=3, padding=1),
                nn.ReLU(),
                nn.Dropout(self.p),
                nn.MaxPool2d(2, 2),

                nn.Conv2d(16, 32, kernel_size=3, padding=1),
                nn.ReLU(),
                nn.Dropout(self.p),
                nn.MaxPool2d(2, 2),

                nn.Flatten()  # Aplanar salida antes de la capa lineal
            )
        else:
            print("Copying encoder from pretrained autoencoder...")
            if copy_encoder:
                self.encoder = nn.Sequential(
                    copy.deepcopy(autoencoder_conv.encoder),
                    nn.Flatten()  #  Aplanar salida antes de la capa lineal
                )
            else:
                self.encoder = nn.Sequential(
                    autoencoder_conv.encoder,
                    nn.Flatten()
                )

        # CLASIFICADOR con 3 capas densas
        self.clasificador = nn.Sequential(
            nn.Linear(32 * 7 * 7, self.n1),  #  Tamaño corregido
            nn.ReLU(),
            nn.Dropout(self.p),

            nn.Linear(self.n1, self.n2),
            nn.ReLU(),
            nn.Dropout(self.p),

            nn.Linear(self.n2, 10)  # Salida de 10 clases
        )

    def forward(self, x):
        x = self.encoder(x)
        #print("Forma después del encoder:", x.shape)  #  Depuración
        x = self.clasificador(x)
        return x